<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">
*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<!--NAVIGATION-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Contents](Index.ipynb) | [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb) >

# The Basics of NumPy Arrays, 数组操作的基础

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.

This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
子数组,分片,重塑,合并

While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.


Get to know them well!



We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays: 数组的属性,大小,维度,内存
- *Indexing of arrays*: Getting and setting the value of individual array elements:数组的索引
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array:数组的分片

- *Reshaping of arrays*: Changing the shape of a given array: 重塑

- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many: 合并/分割

## NumPy Array Attributes, 数组的属性

First let's discuss some useful array attributes.

We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. 

定义随机数组

We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

通过设置随机数,使代码在每次运行的产生的随机数据都是一样的

In [11]:
import numpy as np
np.random.seed(0)  # seed for reproducibility,产生随机数的种子,
 
#for i in range(10):
#    n = np.random.randint(10, size = 6)
#    print (n)
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array,    #size 是数组的类型 ->  shape
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [15]:
print("x3 ndim: ", x3.ndim)  # 维度
print("x3 shape:", x3.shape) # 具体的维度
print("x3 size: ", x3.size)  # 个数的大小

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


(3, 4, 5)

Another useful attribute is the ``dtype``, 
the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

In [16]:
print("dtype:", x3.dtype)  # 数组的类型

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [17]:
print("itemsize:", x3.itemsize, "bytes")  # 单元的字节数
print("nbytes:", x3.nbytes, "bytes")      # 类型的字节数

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements, 索引

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.


np.array数据的索引

In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:



In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [19]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [20]:
x1[-1]

9

In [21]:
x1[-2]

7

In a multi-dimensional array, 
items can be accessed using a comma-separated tuple of indices: 

再多维数组中,可以使用  , 分割数据

In [25]:
x2

x2.shape   

[ y for x in x2 for y in x]  # 按数组的方访问

[3, 5, 2, 4, 7, 6, 8, 8, 1, 6, 7, 7]

In [26]:
x2[0, 0]

3

In [27]:
x2[2, 0]

1

In [29]:
x2  # x2的数据

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [30]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.


This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

np.array 是固定的类型, 赋值会被强制类型转换


In [35]:

x1[0] = 0.14159  # this will be truncated!
x1

array([0, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays, 数组的分片子数组

Just as we can use square brackets to access individual array elements, 

we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.

The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:

``` python
x[start:stop:step]
```

If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [36]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [18]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [20]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [37]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [39]:
x[::-1]  # all elements, reversed, 数组的倒排, 通过分片实现

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [46]:
y = x[0:-1:2]   # 分片是对数组建立新的索引, 对子数组的修改就会对原始数组也进行修改
y
y[2] = 11   
x

array([11,  1,  2,  3, 11,  5,  6,  7,  8,  9])

### Multi-dimensional subarrays, 多维数组的分片

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

array([0, 0, 3, 3, 7, 9])

In [47]:
x2[:2, :3]  # two rows, three columns, 冒号分割分片数据, ,号分割维度

array([[12,  5,  2],
       [ 7,  6,  8]])

In [56]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [57]:
x2[::-1, ::-1] # 先对行进行倒置,在对列进行倒置, => 矩阵的倒置

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns , 数组的索引和分片结合使用

One commonly needed routine is accessing of single rows or columns of an array.

This can be done by combining indexing and slicing,
using an empty slice marked by a single colon (``:``):

In [28]:
print(x2[:, 0])  # first column of x2, 访问第一列

[12  7  1]


In [29]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [30]:
print(x2[0])  # equivalent to x2[0, :]   # 多维数组的索引的方式

[12  5  2  4]


### Subarrays as no-copy views, 

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.


数组分片返回的是数组的view试图, 不是数组的copy, 对分片的修改同时也是对数组的修改

This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:


In [60]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let's extract a $2 \times 2$ subarray from this:

In [32]:
x2_sub = x2[:2, :2]  # 二维数组的分片
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views,

it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

使用对象的copy函数实现对数组的复制


In [62]:
x2_sub_copy = x2[:2, :2].copy()   #  复制数组
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [63]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [65]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays,  对数组进行重新的shape

Another useful type of operation is reshaping of arrays.

The most flexible way of doing this is with the ``reshape`` method.

For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [67]:
np.arange(1,10)  #  [1-10) 的数组

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
grid = np.arange(1, 10).reshape((3, 3))  # 先生成数组, 在对数组进行重塑
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

reshape也不是对数组的copy


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.


This can be done with the ``reshape`` method, 

or more easily done by making use of the ``newaxis`` keyword within a slice operation:



In [92]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

(1, 3)

In [95]:
y = np.arange(1,4)  # 一维数组
y.shape  # 数组的shape 是一维, 第一个索引是列  =>(3,)
z  = y.reshape(1,3)   # 第一个索引是行 =  1, col = 3,(1,3)
z[0,1] = 100   # shape 也是对数组的视图, 不是对数组的复制
x

array([1, 2, 3])

In [96]:
# row vector via newaxis  # 通过newaxis实现行向量,行生成新的索引, 列的元素使用分片的方式获取
x[np.newaxis, ::2]

array([[1, 3]])

In [97]:
# column vector via reshape
x.reshape((3, 1))  # 使用所有的元素reshape,

array([[1],
       [2],
       [3]])

In [98]:
# column vector via newaxis
x[::2, np.newaxis]  # 列是新生成的索引, 按分片获取元素, 在生成新的图形


array([[1],
       [3]])

In [101]:
x = np.arange(1,10)
#x.reshape(3,3)   # 使用shape 必须保持元素的个数一致

x[np.newaxis, ::2]  # 使用newasix能不需要考虑元素的个数问题,新生成的维度 = 1

array([[1, 3, 5, 7, 9]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting, array 合并和拆分

All of the preceding routines worked on single arrays.

It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [102]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])   # 合并np.array
np.concatenate?

You can also concatenate more than two arrays at once:

In [44]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))  # 参数的形式 

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [45]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [103]:
# concatenate along the first axis  # 默认结合第一轴线合并, axis = 0 是第一轴线
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# concatenate along the second axis (zero-indexed)  #  axis = 1 是第二轴线, => 理解轴线!!!!!!!
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [48]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays , 垂直线
np.vstack([x, grid])   # 参数必须能合并

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
# horizontally stack the arrays,水平线
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, ``np.dstack`` will stack arrays along the third axis.  三轴线

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [50]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  #根据元素的个数进行分片
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [104]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [53]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

<!--NAVIGATION-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Contents](Index.ipynb) | [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb) >